-- ✅ MySQL 버전
SELECT *
FROM FOOD_PRODUCT
WHERE PRICE = (SELECT MAX(PRICE) FROM FOOD_PRODUCT);

-- ✅ Oracle 버전
SELECT *
FROM (
    SELECT *
    FROM FOOD_PRODUCT
    ORDER BY PRICE DESC
)
WHERE ROWNUM = 1;
