-- ✅ MySQL 버전
SELECT 
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    (MAX_YEAR.SIZE - SIZE_OF_COLONY) AS YEAR_DEV,
    ID
FROM ECOLI_DATA
JOIN (
    SELECT 
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) AS MAX_YEAR
ON YEAR(ECOLI_DATA.DIFFERENTIATION_DATE) = MAX_YEAR.YEAR
ORDER BY YEAR, YEAR_DEV;
