-- ✅ MySQL 버전
SELECT 
    MONTH(START_DATE) AS MONTH,
    CAR_ID,
    COUNT(HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
  AND CAR_ID IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
        GROUP BY CAR_ID
        HAVING COUNT(*) >= 5
    )
GROUP BY CAR_ID, MONTH
HAVING RECORDS > 0
ORDER BY MONTH ASC, CAR_ID DESC;

-- ✅ Oracle 버전
SELECT 
    EXTRACT(MONTH FROM START_DATE) AS MONTH,
    CAR_ID,
    COUNT(HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE BETWEEN TO_DATE('2022-08-01', 'YYYY-MM-DD') 
                    AND TO_DATE('2022-10-31', 'YYYY-MM-DD')
  AND CAR_ID IN (
      SELECT CAR_ID
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
      WHERE START_DATE BETWEEN TO_DATE('2022-08-01', 'YYYY-MM-DD') 
                          AND TO_DATE('2022-10-31', 'YYYY-MM-DD')
      GROUP BY CAR_ID
      HAVING COUNT(*) >= 5
  )
GROUP BY EXTRACT(MONTH FROM START_DATE), CAR_ID
HAVING COUNT(HISTORY_ID) > 0
ORDER BY MONTH ASC, CAR_ID DESC;
