-- ✅ MySQL 버전
SELECT 
    A.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(BS.SALES * B.PRICE) AS TOTAL_SALES
FROM 
    BOOK_SALES AS BS
    JOIN BOOK AS B ON BS.BOOK_ID = B.BOOK_ID
    JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE 
    BS.SALES_DATE LIKE '2022-01%'
GROUP BY 
    A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY 
    A.AUTHOR_ID ASC, B.CATEGORY DESC;

-- ✅ Oracle 버전
SELECT 
    A.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(BS.SALES * B.PRICE) AS TOTAL_SALES
FROM 
    BOOK_SALES BS
    JOIN BOOK B ON BS.BOOK_ID = B.BOOK_ID
    JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE 
    TO_CHAR(BS.SALES_DATE, 'YYYY-MM') = '2022-01'
GROUP BY 
    A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY 
    A.AUTHOR_ID ASC, B.CATEGORY DESC;
