-- ✅ MySQL 버전
SELECT 
  RI.FOOD_TYPE,
  RI.REST_ID,
  RI.REST_NAME,
  RI.FAVORITES
FROM 
  REST_INFO RI
JOIN (
  SELECT 
    FOOD_TYPE,
    MAX(FAVORITES) AS MaxFavorites
  FROM 
    REST_INFO
  GROUP BY 
    FOOD_TYPE
) Sub ON RI.FOOD_TYPE = Sub.FOOD_TYPE AND RI.FAVORITES = Sub.MaxFavorites
ORDER BY 
  RI.FOOD_TYPE DESC;

-- ✅ Oracle 버전
SELECT
  FOOD_TYPE,
  REST_ID,
  REST_NAME,
  FAVORITES
FROM (
  SELECT
    FOOD_TYPE,
    REST_ID,
    REST_NAME,
    FAVORITES,
    RANK() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS RNK
  FROM REST_INFO
)
WHERE RNK = 1
ORDER BY FOOD_TYPE DESC;
