-- ✅ MySQL 버전
SELECT 
  IT.INGREDIENT_TYPE, 
  SUM(FH.TOTAL_ORDER) AS TOTAL_ORDER
FROM 
  FIRST_HALF AS FH
JOIN 
  ICECREAM_INFO AS IT ON FH.FLAVOR = IT.FLAVOR
GROUP BY 
  IT.INGREDIENT_TYPE;

-- ✅ Oracle 버전
SELECT 
  INGREDIENT_TYPE,
  (SELECT SUM(TOTAL_ORDER)
     FROM FIRST_HALF FH
    WHERE FH.FLAVOR IN (
      SELECT FLAVOR 
      FROM ICECREAM_INFO IT2
      WHERE IT2.INGREDIENT_TYPE = IT.INGREDIENT_TYPE
    )
  ) AS TOTAL_ORDER
FROM 
  ICECREAM_INFO IT
GROUP BY 
  INGREDIENT_TYPE;
