-- ✅ MySQL 버전
SELECT 
    ANIMAL_TYPE, 
    COUNT(ANIMAL_TYPE) AS count
FROM 
    ANIMAL_INS
GROUP BY 
    ANIMAL_TYPE
ORDER BY 
    ANIMAL_TYPE = 'CAT' DESC;

-- ✅ Oracle 버전
SELECT 
    ANIMAL_TYPE, 
    COUNT(*) AS count
FROM 
    ANIMAL_INS
GROUP BY 
    ANIMAL_TYPE
ORDER BY 
    CASE WHEN ANIMAL_TYPE = 'CAT' THEN 1 ELSE 0 END DESC;
