-- ✅ MySQL 버전
SELECT NAME, COUNT(NAME) AS COUNT
FROM ANIMAL_INS
GROUP BY NAME
HAVING COUNT(NAME) > 1
ORDER BY NAME;

-- ✅ Oracle 버전
SELECT NAME, (
    SELECT COUNT(*) 
    FROM ANIMAL_INS A2 
    WHERE A2.NAME = A1.NAME
) AS NAME_COUNT
FROM ANIMAL_INS A1
WHERE NAME IS NOT NULL
  AND (
    SELECT COUNT(*) 
    FROM ANIMAL_INS A2 
    WHERE A2.NAME = A1.NAME
) > 1
GROUP BY NAME
ORDER BY NAME;
