-- ✅ MySQL 버전
SELECT 
    YEAR(SALES_DATE) AS YEAR, 
    MONTH(SALES_DATE) AS MONTH, 
    GENDER, 
    COUNT(DISTINCT OS.USER_ID) AS USERS
FROM 
    ONLINE_SALE AS OS
JOIN 
    USER_INFO AS UI ON OS.USER_ID = UI.USER_ID
WHERE 
    GENDER IS NOT NULL
GROUP BY 
    YEAR, MONTH, GENDER
ORDER BY 
    YEAR, MONTH, GENDER;

-- ✅ Oracle 버전
SELECT 
    EXTRACT(YEAR FROM SALES_DATE) YEAR,
    EXTRACT(MONTH FROM SALES_DATE) MONTH,
    GENDER,
    COUNT(DISTINCT OS.USER_ID) USERS
FROM 
    ONLINE_SALE OS
JOIN 
    USER_INFO UI ON OS.USER_ID = UI.USER_ID
WHERE 
    GENDER IS NOT NULL
GROUP BY 
    EXTRACT(YEAR FROM SALES_DATE),
    EXTRACT(MONTH FROM SALES_DATE),
    GENDER
ORDER BY 
    EXTRACT(YEAR FROM SALES_DATE),
    EXTRACT(MONTH FROM SALES_DATE),
    GENDER;
