-- ✅ MySQL 버전
SELECT 
    HOUR(DATETIME) AS HOUR, 
    COUNT(*) AS COUNT
FROM 
    ANIMAL_OUTS
WHERE 
    HOUR(DATETIME) BETWEEN 9 AND 19
GROUP BY 
    HOUR
ORDER BY 
    HOUR ASC;

-- ✅ Oracle 버전
SELECT 
    TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) AS HOUR,
    COUNT(*) AS COUNT
FROM 
    ANIMAL_OUTS
WHERE 
    TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) BETWEEN 9 AND 19
GROUP BY 
    TO_NUMBER(TO_CHAR(DATETIME, 'HH24'))
ORDER BY 
    HOUR ASC;
