-- ✅ MySQL 버전
SET @HOUR := -1;

SELECT 
    @HOUR := @HOUR + 1 AS HOUR,
    (SELECT COUNT(*) 
     FROM ANIMAL_OUTS 
     WHERE HOUR(DATETIME) = @HOUR) AS COUNT
FROM 
    ANIMAL_OUTS
WHERE 
    @HOUR < 23;

-- ✅ Oracle 버전
WITH HOURS AS (
    SELECT LEVEL - 1 AS HOUR
    FROM DUAL
    CONNECT BY LEVEL <= 24
)
SELECT 
    H.HOUR,
    (SELECT COUNT(*) 
     FROM ANIMAL_OUTS 
     WHERE TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) = H.HOUR) AS COUNT
FROM 
    HOURS H
ORDER BY 
    H.HOUR;
