-- ✅ MySQL 버전
SELECT 
    COUNT(FI.ID) AS FISH_COUNT, 
    FISH_NAME
FROM 
    FISH_INFO FI
INNER JOIN 
    FISH_NAME_INFO AS FNI 
ON 
    FI.FISH_TYPE = FNI.FISH_TYPE
GROUP BY 
    FNI.FISH_NAME
ORDER BY 
    FISH_COUNT DESC;
