# SELECT

## 🔻 조건에 부합하는 중고거래 댓글 조회하기 (Level 1)

## mysql

SELECT 
    TITLE, 
    UGB.BOARD_ID, 
    UGR.REPLY_ID, 
    UGR.WRITER_ID, 
    UGR.CONTENTS, 
    DATE_FORMAT(UGR.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_REPLY AS UGR 
LEFT JOIN USED_GOODS_BOARD AS UGB
ON UGR.BOARD_ID = UGB.BOARD_ID
WHERE SUBSTR(UGB.CREATED_DATE, 1,7)= '2022-10'
ORDER BY UGR.CREATED_DATE ASC, TITLE ASC;