-- ✅ MySQL 버전
SELECT 
    TITLE, 
    UGB.BOARD_ID, 
    UGR.REPLY_ID, 
    UGR.WRITER_ID, 
    UGR.CONTENTS, 
    DATE_FORMAT(UGR.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_REPLY AS UGR 
LEFT JOIN USED_GOODS_BOARD AS UGB
    ON UGR.BOARD_ID = UGB.BOARD_ID
WHERE SUBSTR(UGB.CREATED_DATE, 1, 7) = '2022-10'
ORDER BY UGR.CREATED_DATE ASC, TITLE ASC;

-- ✅ Oracle 버전
SELECT 
    UGB.TITLE, 
    UGB.BOARD_ID, 
    UGR.REPLY_ID, 
    UGR.WRITER_ID, 
    UGR.CONTENTS, 
    TO_CHAR(UGR.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE
FROM USED_GOODS_REPLY UGR
LEFT JOIN USED_GOODS_BOARD UGB
    ON UGR.BOARD_ID = UGB.BOARD_ID
WHERE TO_CHAR(UGB.CREATED_DATE, 'YYYY-MM') = '2022-10'
ORDER BY UGR.CREATED_DATE ASC, UGB.TITLE ASC;
