# SELECT

## 🔻 서울에 위치한 식당 목록 출력하기 (Level 4)

SELECT
    RR.REST_ID,
    RI.REST_NAME,
    RI.FOOD_TYPE,
    RI.FAVORITES,
    RI.ADDRESS,
    ROUND(AVG(RR.REVIEW_SCORE), 2) AS SCORE
FROM 
    REST_REVIEW AS RR
JOIN 
    REST_INFO AS RI ON RR.REST_ID = RI.REST_ID
WHERE 
    RI.ADDRESS LIKE '서울%'
GROUP BY 
    RR.REST_ID
ORDER BY 
    SCORE DESC,
    RI.FAVORITES DESC;