-- ✅ MySQL 버전
SELECT FH.FLAVOR
FROM FIRST_HALF FH
JOIN ICECREAM_INFO II ON FH.FLAVOR = II.FLAVOR
WHERE FH.TOTAL_ORDER > 3000
  AND II.INGREDIENT_TYPE = 'fruit_based'
ORDER BY FH.TOTAL_ORDER DESC;


-- ✅ Oracle 버전
SELECT FLAVOR
FROM (
    SELECT FH.FLAVOR, FH.TOTAL_ORDER
    FROM FIRST_HALF FH, ICECREAM_INFO II
    WHERE FH.FLAVOR = II.FLAVOR
      AND FH.TOTAL_ORDER > 3000
      AND II.INGREDIENT_TYPE = 'fruit_based'
)
ORDER BY TOTAL_ORDER DESC;
