-- ✅ MySQL 버전
SELECT 
    FACTORY_ID,
    FACTORY_NAME,
    ADDRESS
FROM FOOD_FACTORY
WHERE ADDRESS LIKE '강원도%'
ORDER BY FACTORY_ID ASC;


-- ✅ Oracle 버전
SELECT 
    FACTORY_ID,
    FACTORY_NAME,
    ADDRESS
FROM FOOD_FACTORY
WHERE INSTR(ADDRESS, '강원도') = 1
ORDER BY FACTORY_ID ASC;
