-- ✅ MySQL 버전
SELECT FLAVOR
FROM FIRST_HALF
ORDER BY TOTAL_ORDER DESC, SHIPMENT_ID ASC;

-- ✅ Oracle 버전
SELECT FLAVOR
FROM (
    SELECT FLAVOR, TOTAL_ORDER, SHIPMENT_ID
    FROM FIRST_HALF
)
ORDER BY TOTAL_ORDER DESC, SHIPMENT_ID ASC;
