-- ✅ MySQL 버전
SELECT 
    BOOK_ID, 
    DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK 
WHERE PUBLISHED_DATE LIKE '2021%' 
  AND CATEGORY = '인문'
ORDER BY PUBLISHED_DATE;


-- ✅ Oracle 버전
SELECT 
    BOOK_ID,
    TO_CHAR(PUBLISHED_DATE, 'YYYY-MM-DD') AS PUBLISHED_DATE
FROM BOOK
WHERE CATEGORY = '인문'
  AND PUBLISHED_DATE BETWEEN TO_DATE('2021-01-01', 'YYYY-MM-DD')
                         AND TO_DATE('2021-12-31', 'YYYY-MM-DD')
ORDER BY PUBLISHED_DATE ASC;