-- ✅ MySQL 버전
SELECT 
    ROUND(AVG(DAILY_FEE), 0) AS AVERAGE_FEE
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_TYPE = 'SUV';

-- ✅ Oracle 버전
SELECT 
    ROUND(AVG(CASE WHEN CAR_TYPE = 'SUV' THEN DAILY_FEE END)) AS AVERAGE_FEE
FROM CAR_RENTAL_COMPANY_CAR;
