-- ✅ MySQL 버전
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS 
ORDER BY ANIMAL_ID ASC, NAME ASC;

-- ✅ Oracle 버전
SELECT ANIMAL_ID, NAME
FROM (
    SELECT ANIMAL_ID, NAME
    FROM ANIMAL_INS
    ORDER BY ANIMAL_ID, NAME
);
