-- ✅ MySQL 버전
SELECT ANIMAL_ID, NAME, DATETIME
FROM ANIMAL_INS
ORDER BY NAME, DATETIME DESC;

-- ✅ Oracle 버전
SELECT ANIMAL_ID, NAME, DATETIME
FROM (
    SELECT ANIMAL_ID, NAME, DATETIME
    FROM ANIMAL_INS
    ORDER BY NAME, DATETIME DESC
);
