-- ✅ MySQL 버전
SELECT COUNT(USER_ID) AS USERS
FROM (
    SELECT USER_ID, AGE
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
) AS SubQuery
WHERE AGE BETWEEN 20 AND 29;

-- ✅ Oracle 버전
SELECT COUNT(USER_ID) AS USERS
FROM (
    SELECT USER_ID, AGE
    FROM USER_INFO
    WHERE TO_CHAR(JOINED, 'YYYY') = '2021'
) 
WHERE AGE BETWEEN 20 AND 29;
