-- ✅ MySQL 버전
WITH RECURSIVE Generation AS (
    SELECT ID, PARENT_ID, 1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    SELECT E.ID, E.PARENT_ID, G.GEN + 1
    FROM ECOLI_DATA E
    JOIN Generation G ON E.PARENT_ID = G.ID
)
SELECT ID
FROM Generation
WHERE GEN = 3
ORDER BY ID;
